### ISSUE TITLE
Feature request: save Export to io.Writer and Import from io.Reader

### ISSUE THREAD

**Issue by erikdubbelboer** [philippgille/chromem-go#70]
Currently `Export` and `Import` use files. It would be nicer if we have versions with `io.Writer` and `io.Reader` so we can use other data sources such as S3 or HTTP requests.

**Comment by philippgille** [comment]
Yup, makes sense!

Do you have in mind more something like `db.Export(myWriter)` where the user can / has to add compression and encryption by himself, or more `db.Export(myWriter, true, "mySecret")` which would add gzip compression and AES encryption like the current export/import do?

**Comment by erikdubbelboer** [comment]
Since the code is already there I think the second option would be nicer. If users want to do their own compression and encryption they still can be using `db.Export(myWriter, false, "")`.

**Comment by philippgille** [comment]
Sounds good :+1: 

I started already, but might only finish it over the weekend.

**Comment by philippgille** [comment]
Hi @erikdubbelboer , I've implemented it. Would you mind reviewing:

- The export/write part: https://github.com/philippgille/chromem-go/pull/71
- The import/read part: https://github.com/philippgille/chromem-go/pull/72
- The example code that uses both: https://github.com/philippgille/chromem-go/pull/73 (still draft)

**Comment by erikdubbelboer** [comment]
Looks good 👍

**Comment by philippgille** [comment]
Thanks!

Merged
