### ISSUE TITLE
Change license to a more permissive one

### ISSUE THREAD

**Issue by philippgille** [philippgille/chromem-go#86]
Currently chromem-go is licensed under the AGPL, which is considered "strong copyleft", and is similar to (but even stricter than) the GPL.

The LGPL is more permissive, as it allows the use of a library in proprietary code, but mostly for *dynamic* linking. To my knowledge the story for static linking is more complicated. With Go this is an issue, as libraries are statically linked by default.

MIT and Apache are too permissive in my opinion. People could change the library without sharing the changes with (and thus giving back to) the community.

The middle ground seem to be MPL, EPL and CDDL. They allow the *use* of the unchanged library in commercial, proprietary software. Only *changes* to the library have to be open sourced.

Resources:
- https://choosealicense.com/licenses/
- https://www.tldrlegal.com/browse
- https://opensource.org/licenses
- https://fossa.com/blog/open-source-software-licenses-101-eclipse-public-license/

----

Pinging all contributors, because I would like to have (or may legally require) your consent to change the license: @iwilltry42 , @erikdubbelboer , @codefromthecrypt , @rinor

**Comment by codefromthecrypt** [comment]
My 2p is to go more permissive if the desire is embedding.

Tools like chromem-go may end up deeply embedded, and org policy (such as CNCF etc) will not be able to use a dependency or sub dependency on a non-permissive license without an exception clause. Meaning it is more fundamental than mechanics. So, even if there is no likelihood to need a feature beyond linking, the license choice at all will trip audits and hold back adoption.

So, you might want to check on various incubating CNCF projects and see how they've handled license exceptions, or possibly rule out this class entirely if this sort of governance isn't something to optimize for. Of course, I could have summarized incorrectly, too!

**Comment by iwilltry42** [comment]
From personal preference and previous experience in OSS so far, I'd vote for Apache 2.0 or MIT.
This will probably also boost adoption.
TBH I never heard about those alternatives you're considering, so I don't have a strong opinion on those really.
However, I would fear that those uncommon licences may scare off users/customers/contributors.

**Comment by erikdubbelboer** [comment]
I also always go for MIT. People making changes and not giving back is a risk, but you usually don't want those people participating either way. Any decent developer making useful changes would contribute back to an open source project.

**Comment by philippgille** [comment]
It's great to see all of you are open to move to a more permissive license! Even beyond the ones I had in mind.

Regarding their popularity:

- The MPL is used by Mozilla products like Firefox and Thunderbird, but also by others like [LibreOffice](https://www.libreoffice.org/about-us/licenses), [Syncthing](https://github.com/syncthing/syncthing/blob/a8db3351ae920a27b4c0ed1f9fe6da1e80a2b8e6/LICENSE), [OpenTofu](https://github.com/opentofu/opentofu/blob/568ff66befdda27b758843bcbac11a32c9d757b8/LICENSE) (the Terraform fork after Hashicorp went BSL). Popular enough to be included in the 8 licenses on https://choosealicense.com/licenses
- The EPL is used by most (or all?) Eclipse projects, like the Eclipse IDE (one of the most popular Java IDEs), Che and Theia (web based IDEs), Jetty (web framework). But indeed not so popular outside the Eclipse ecosystem

Regarding others not giving back:

I'm less worried about individuals, but more about companies. The MPL allows them to use the library in closed source software, but at least if they make changes to the library they have to make those available to the community. I think it's a fair deal between open source maintainers/contributors and for-profit companies.

And with Apache/MIT, once a project is licensed with them, the "genie is out of the bottle". With that I mean it's easy to move from a restrictive to a permissive license, but hard to go the other direction, because a license change doesn't apply retroactively.

If we go with MPL for now, we can still change it to Apache/MIT in the future.

=> I'll change to MPL for now as an iterative step, but I'll keep an open mind to go further (more permissive) in the future. Especially if one of you existing contributors has a requirement for it (i.e. you want to distribute software that uses a closed source modified version of the library).

**Comment by codefromthecrypt** [comment]
sounds like progress, and understand the trade-offs you are looking at.

Note that for a CNCF project to use this library, it will need to go through an exception process, as MPL is not in the [allow list](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).

Basically, someone needs to submit the request [here](https://github.com/cncf/foundation/blob/main/license-exceptions/CNCF-licensing-exceptions.csv) in order to use it. You can keep note of this when that occurs.

**Comment by iwilltry42** [comment]
I just read up on MPL and think it's a good first step and is not too restrictive and especially it's generally compatible with other open source licences 👍

**Comment by philippgille** [comment]
> Note that for a CNCF project to use this library, it will need to go through an exception process, as MPL is not in the [allow list](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).
> 
> Basically, someone needs to submit the request [here](https://github.com/cncf/foundation/blob/main/license-exceptions/CNCF-licensing-exceptions.csv) in order to use it. You can keep note of this when that occurs.

Ah didn't know that, I'll keep it in mind, thanks :+1:
